### PR TITLE
Do not regenerate files when they are up-to-date

### PR DESCRIPTION
**Pull request by eugeneo**
GYP generates makefiles that always rebuild targets with multiple outputs. This change makes the Python script touch less files, reducing time on rebuild.

### CODE REVIEW

**Comment by ofrobots** [comment]
Could you make the change upstream in repenaxa/v8_inspector? I can roll the dep once the change is there.

**Comment by eugeneo** [comment]
Done

**Comment by ofrobots** [comment]
Much better, but I still get a small amount of work done on each build, after a complete make.

```
~/src/node v8-inspector
❯ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C out BUILDTYPE=Release V=1
  touch deps_v8_inspector_platform_inspector_protocol_protocol_gyp_protocol_sources_target_generateInspectorProtocolBackendSources.intermediate
  LD_LIBRARY_PATH=/Users/ofrobots/src/node/out/Release/lib.host:/Users/ofrobots/src/node/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps/v8_inspector/platform/inspector_protocol; mkdir -p /Users/ofrobots/src/node/out/Release/obj/gen/blink/platform/inspector_protocol; python CodeGenerator.py ../../devtools/protocol.json --output_dir "/Users/ofrobots/src/node/out/Release/obj/gen/blink/platform/inspector_protocol"
rm deps_v8_inspector_platform_inspector_protocol_protocol_gyp_protocol_sources_target_generateInspectorProtocolBackendSources.intermediate
ln -fs out/Release/node node
```

**Comment by ofrobots** [comment]
Pushed as https://github.com/nodejs/node/pull/6792/commits/ed8931b6082f3ba85a06da6111a194190f3faab7.

**Comment by eugeneo** [comment]
Yeah... GYP still wants to rerun the generator on each rebuild - I have not
found a solution for that. It's just that the generator will no longer
touch files, so they will not get rebuilt, etc.

**Pull request closed without merging**
